az-configuration:
- name: {{ index (ds "data").azs 0 }}
- name: {{ index (ds "data").azs 1 }}
- name: {{ index (ds "data").azs 2 }}
network-assignment:
  network:
    name: pks-infra
  other_availability_zones: []
  singleton_availability_zone:
    name: {{ index (ds "data").azs 0 }}
networks-configuration:
  icmp_checks_enabled: false
  networks:
  - name: pks-infra
    subnets:
    {{ range $index, $element := (ds "data").infrastructure_subnets }}
    - iaas_identifier: {{ index (ds "data").infrastructure_subnet_ids $index }}
      cidr: {{ index (ds "data").infrastructure_subnet_cidrs $index}}
      dns: {{ (ds "data").dns }}
      gateway: {{ index (ds "data").infrastructure_subnet_gateways $index }}
      reserved_ip_ranges: {{ index (ds "data").subnet_mgmt_reserved $index }}
      availability_zone_names:
      - {{ index (ds "data").infrastructure_subnet_availability_zones $index }}
    {{ end }}
  - name: pks
    subnets:
    {{ range $index, $element := (ds "data").pks_subnets }}
    - iaas_identifier: {{ index (ds "data").pks_subnet_ids $index }}
      cidr: {{ index (ds "data").pks_subnet_cidrs $index}}
      dns: {{ (ds "data").dns }}
      gateway: {{ index (ds "data").pks_subnet_gateways $index }}
      reserved_ip_ranges: {{ index (ds "data").subnet_pks_reserved $index }}
      availability_zone_names:
      - {{ index (ds "data").pks_subnet_availability_zones $index }}
    {{ end }}
  - name: pks-services
    subnets:
    {{ range $index, $element := (ds "data").services_subnets }}
    - iaas_identifier: {{ index (ds "data").services_subnet_ids $index }}
      cidr: {{ index (ds "data").services_subnet_cidrs $index}}
      dns: {{ (ds "data").dns }}
      gateway: {{ index (ds "data").services_subnet_gateways $index }}
      reserved_ip_ranges: {{ index (ds "data").subnet_pks_svc_reserved $index }}
      availability_zone_names:
      - {{ index (ds "data").services_subnet_availability_zones $index }}
    {{ end }}
properties-configuration:
  director_configuration:
    allow_legacy_agents: true
    blobstore_type: local
    bosh_recreate_on_next_deploy: false
    bosh_recreate_persistent_disks_on_next_deploy: false
    database_type: internal
    director_worker_count: 5
    encryption:
      keys: []
      providers: []
    hm_emailer_options:
      enabled: false
    hm_pager_duty_options:
      enabled: false
    identification_tags: {}
    keep_unreachable_vms: false
    local_blobstore_options:
      tls_enabled: true
    ntp_servers_string: 0.amazon.pool.ntp.org,1.amazon.pool.ntp.org,2.amazon.pool.ntp.org,3.amazon.pool.ntp.org
    post_deploy_enabled: true
    resurrector_enabled: true
    retry_bosh_deploys: false
    skip_director_drain: true
  dns_configuration:
    excluded_recursors: []
    handlers: []
  iaas_configuration:
    additional_cloud_properties: {}
    iam_instance_profile: {{ (ds "data").ops_manager_iam_instance_profile_name }}
    name: {{ (ds "data").region }}
    key_pair_name: {{ (ds "data").ops_manager_ssh_public_key_name }}
    ssh_private_key: |
{{ (ds "data").ops_manager_ssh_private_key | strings.Indent 10 }}
    region: {{ (ds "data").region }}
    security_group: {{ (ds "data").vms_security_group_id }}
  security_configuration:
    generate_vm_passwords: true
    opsmanager_root_ca_trusted_certs: true
  syslog_configuration:
    enabled: false
resource-configuration:
  compilation:
    instances: automatic
    instance_type:
      id: automatic
    internet_connected: true
  director:
    instances: automatic
    persistent_disk:
      size_mb: automatic
    instance_type:
      id: automatic
    internet_connected: true
vmextensions-configuration:
- name: pks-api-security-groups
  cloud_properties:
    security_groups: ["pks_api_lb_security_group", "vms_security_group"]
