product-name: pivotal-container-service
product-properties:
  .pivotal-container-service.pks_tls:
    value:
      cert_pem: |
{{ (ds "data").ssl_cert | strings.Indent 10 }}
      private_key_pem: |
{{ (ds "data").ssl_private_key | strings.Indent 10 }}
  .properties.bosh-metric-sink-node-exporter:
    value: true
  .properties.bosh-metric-sink-outputs:
    value: |
      [[outputs.discard]]
  .properties.node_exporter_deploy:
    value: true
  .properties.cloud_provider:
    value: AWS
  .properties.cloud_provider.aws.iam_instance_profile_master: 
    value: {{ (ds "data").pks_master_iam_instance_profile_name }}
  .properties.cloud_provider.aws.iam_instance_profile_worker: 
    value: {{ (ds "data").pks_worker_iam_instance_profile_name }}
  .properties.log_sink_resources_deploy:
    value: true
  .properties.metric_sink_resources_deploy:
    value: true
  .properties.network_selector:
    value: flannel
  .properties.network_selector.flannel.pod_network_cidr:
    value: 10.200.0.0/16
  .properties.network_selector.flannel.service_cluster_cidr:
    value: 10.100.200.0/24
  .properties.pks-vrli:
    value: disabled
  .properties.pks-vrops:
    value: disabled
  .properties.pks_api_hostname:
    value: {{ (ds "data").pks_api_endpoint }}
  .properties.plan1_selector:
    value: Plan Active
  .properties.plan1_selector.active.allow_privileged_containers:
    value: false
  .properties.plan1_selector.active.master_az_placement:
    value:
    - {{ index (ds "data").azs 0 }}
  .properties.plan1_selector.active.worker_az_placement:
    value:
    - {{ index (ds "data").azs 0 }}
    - {{ index (ds "data").azs 1 }}
    - {{ index (ds "data").azs 2 }}
  .properties.plan1_selector.active.description:
    value: 'Example: This plan will configure a lightweight kubernetes cluster. Not
      recommended for production workloads.'
  .properties.plan1_selector.active.kubelet_drain_delete_local_data:
    value: true
  .properties.plan1_selector.active.kubelet_drain_force:
    value: true
  .properties.plan1_selector.active.kubelet_drain_force_node:
    value: false
  .properties.plan1_selector.active.kubelet_drain_grace_period:
    value: 10
  .properties.plan1_selector.active.kubelet_drain_ignore_daemonsets:
    value: true
  .properties.plan1_selector.active.kubelet_drain_timeout:
    value: 0
  .properties.plan1_selector.active.master_instances:
    value: 1
  .properties.plan1_selector.active.max_worker_instances:
    value: 50
  .properties.plan1_selector.active.worker_instances:
    value: 3
  .properties.plan1_selector.active.name:
    value: small
  .properties.plan2_selector:
    value: Plan Inactive
  .properties.plan3_selector:
    value: Plan Inactive
  .properties.plan4_selector:
    value: Plan Inactive
  .properties.plan5_selector:
    value: Plan Inactive
  .properties.plan6_selector:
    value: Plan Inactive
  .properties.plan7_selector:
    value: Plan Inactive
  .properties.plan8_selector:
    value: Plan Inactive
  .properties.plan9_selector:
    value: Plan Inactive
  .properties.plan10_selector:
    value: Plan Inactive
  .properties.plan11_selector:
    value: Plan Inactive
  .properties.plan12_selector:
    value: Plan Inactive
  .properties.plan13_selector:
    value: Plan Inactive
  .properties.proxy_selector:
    value: Disabled
  .properties.syslog_selector:
    value: disabled
  .properties.telemetry_selector:
    value: disabled
  .properties.telemetry_installation_purpose_selector:
    value: not_provided
  .properties.uaa:
    value: internal
  .properties.oidc_selector:
    value: enabled
  .properties.oidc_selector.enabled.groups_claim:
    value: roles
  .properties.oidc_selector.enabled.groups_prefix:
    value: 'oidc:'
  .properties.oidc_selector.enabled.username_claim:
    value: user_name
  .properties.oidc_selector.enabled.username_prefix:
    value: 'oidc:'
  .properties.uaa_pks_cli_access_token_lifetime:
    value: 600
  .properties.uaa_pks_cli_refresh_token_lifetime:
    value: 21600
  .properties.uaa_pks_cluster_client_access_token_lifetime:
    value: 600
  .properties.uaa_pks_cluster_client_refresh_token_lifetime:
    value: 21600
  .properties.vm_extensions:
    value:
    - public_ip
  .properties.wavefront:
    value: disabled
  .properties.worker_max_in_flight:
    value: 4
network-properties:
  network:
    name: pks 
  other_availability_zones:
  - name: {{ index (ds "data").azs 0 }}
  - name: {{ index (ds "data").azs 1 }}
  - name: {{ index (ds "data").azs 2 }}
  service_network: 
    name: pks-services
  singleton_availability_zone:
    name: {{ index (ds "data").azs 0 }}
resource-config:
  pivotal-container-service:
      instances: automatic
      persistent_disk:
        size_mb: automatic
      instance_type:
        id: automatic
      internet_connected: true
      elb_names:
      - alb:{{ index (ds "data").pks_api_target_groups 0 }}
      - alb:{{ index (ds "data").pks_api_target_groups 1 }}
      additional_vm_extensions:
      - pks-api-security-groups
errand-config:
  delete-all-clusters:
    pre-delete-state: true
  pks-nsx-t-precheck:
    post-deploy-state: false
  smoke-tests:
    post-deploy-state: true
  upgrade-all-service-instances:
    post-deploy-state: true
  wavefront-alert-creation:
    post-deploy-state: false
  wavefront-alert-deletion:
    pre-delete-state: false
